# api version of deployment is apps/v1
# kubectl 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ds
 labels:
  env: prod
spec:
 replicas: 4
 selector:
  matchLabels:
   env: prd
 template:
  metadata:
   name: pod
   labels:
    env: prd
  spec:
   containers:
   - name: nginx
     image: nginx
