apiVersion: v1
kind: Pod
metadata:
 name: pod
 labels:
  app: na
spec:
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: env
         operator: In
         values:
         - dev
  containers:
   - name: nginx
     image: nginx
