apiVersion: apps/v1
kind: Deployment
metadata:
 name: ns
 labels:
  test: ns
spec:
 replicas: 2
 selector:
  matchLabels:
   app: ns
 template:
  metadata:
   name: pod
   labels:
    app: ns
  spec:
   nodeSelector:
    env: dev
   containers:
   - name: nginx
     image: nginx
