# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# Invoke jobs via workflows
jobs:
  build-on-tag:
    docker:
        - image: cimg/base:stable
      
    steps:
       - run: 
          name: "hello"
          command: |
            echo ${CUSTOM_TAG}
          #    echo "CUSTOM_TAG=$( echo "${CIRCLE_TAG}" | sed 's/client-//g' )"  >> $BASH_ENV
           #   source $BASH_ENV
              
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build-on-tag:
          tag: ${CUSTOM_TAG}
          pre-steps: 
            - run: 
              name: "pre-steps-for-job"
              command: |
                  echo "CUSTOM_TAG=$( echo "${CIRCLE_TAG}" | sed 's/client-//g' )"  >> $BASH_ENV
                  source $BASH_ENV
                  echo ${CUSTOM_TAG}
          filters:
              tags:
                only: /^client-.*/
         # filters:
          #  tags:
          #     only: /^client-.*/
          #  branches:
          #     ignore: /.*/
